sudo: true

language: java
jdk: oraclejdk8

before_install:
  - export SKIP_OKBUCK=true
  - export EXTRA_OKBUCK_ARGS="--quiet --stacktrace"
  - export ANDROID_HOME="$HOME"/android-sdk
  - mkdir -p "$ANDROID_HOME"
  - export ANDROID_SDK_FILE_NAME=sdk-tools-linux-3859397.zip
  - sudo apt-get update -q
  - sudo apt-get install -y curl unzip
  - curl --fail https://dl.google.com/android/repository/$ANDROID_SDK_FILE_NAME --silent --location --output $ANDROID_SDK_FILE_NAME
  - unzip -qq $ANDROID_SDK_FILE_NAME -d "$ANDROID_HOME"
  - rm $ANDROID_SDK_FILE_NAME
  - export ANDROID_SDK_INSTALL_COMPONENT="echo \"y\" | \"$ANDROID_HOME\"/tools/bin/sdkmanager > /dev/null"
  - eval $ANDROID_SDK_INSTALL_COMPONENT '"tools"'
  - eval $ANDROID_SDK_INSTALL_COMPONENT '"platform-tools"'
  - eval $ANDROID_SDK_INSTALL_COMPONENT '"build-tools;27.0.1"'
  - eval $ANDROID_SDK_INSTALL_COMPONENT '"platforms;android-27"'
  - eval $ANDROID_SDK_INSTALL_COMPONENT '"extras;android;m2repository"'
  - export PATH="$PATH:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator"

install:
  - echo "Override default Travis install step to avoid unnecessary './gradlew assemble'."

script:
  - SKIP_OKBUCK= ./buckw --version
  - ./buckw targets --type android_binary android_instrumentation_apk java_test groovy_test robolectric_test kotlin_test scala_test | xargs ./buckw build -v 0
  - ./buckw targets --type genrule | grep -v lintErrorLibrary | xargs ./buckw build -v 0
  - ./tooling/ci/lint_integration_test.sh
  - ./buckw test --include unit

notifications:
  email: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - buck-out/cache
    - $HOME/.gradle/caches/modules-2/
    - $HOME/.gradle/wrapper/