version: 2

defaults: &defaults
  working_directory: ~/okbuck
  resource_class: xlarge
  docker:
    - image: circleci/android:api-28-alpha
  environment:
    SKIP_OKBUCK: true
    NO_BUCKD: 1
    EXTRA_OKBUCK_ARGS: --stacktrace
    JVM_OPTS: -Xmx3072m

aliases:
  - &restore-wrapper-cache
    restore_cache:
        keys:
          - gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
  - &restore-gradle-cache
    restore_cache:
        keys:
          - gradle-cache-{{ checksum "dependencies.gradle" }}
  - &setup
    run:
        name: Perform Setup
        command: |-
          ./tooling/ci/ensure-android-sdk-licenses.sh && \
          SKIP_OKBUCK= EXTRA_OKBUCK_ARGS="-Dorg.gradle.daemon=false" ./buckw --version && \
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          # Temporary till #798 is resolved upstream
          RESOLVED_KOTLIN_HOME=$(./buckw build //.okbuck/workspace/kotlin_home:kotlin_home --show-output | awk '{print $2}')
          sed -i.bak "s://.okbuck/workspace/kotlin_home\:kotlin_home:${RESOLVED_KOTLIN_HOME}:g" .okbuck/config/okbuck.buckconfig
        shell: "/bin/bash"
  - &save-wrapper-cache
    save_cache:
        paths:
          - ~/.gradle/caches/modules-2/
        key: gradle-cache-{{ checksum "dependencies.gradle" }}
  - &save-gradle-cache
    save_cache:
        paths:
          - ~/.gradle/wrapper/
        key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *restore-wrapper-cache
      - *restore-gradle-cache
      - *setup
      - *save-wrapper-cache
      - *save-gradle-cache
      - run:
          name: Build all non lint targets
          command: ./buckw targets //... --type android_binary android_instrumentation_apk java_test groovy_test robolectric_test kotlin_test scala_test | xargs ./buckw build
          shell: "/bin/bash"
  lint:
    <<: *defaults
    steps:
      - checkout
      - *restore-wrapper-cache
      - *restore-gradle-cache
      - *setup
      - *save-wrapper-cache
      - *save-gradle-cache
      - run:
          name: Build all lint targets, except for lint error library
          command: |-
            ./buckw targets //... --type genrule | grep -v lintErrorLibrary | xargs ./buckw build && \
            ./tooling/ci/lint_integration_test.sh
          shell: "/bin/bash"
  unit:
    <<: *defaults
    steps:
      - checkout
      - *restore-wrapper-cache
      - *restore-gradle-cache
      - *setup
      - *save-wrapper-cache
      - *save-gradle-cache
      - run:
          name: Run unit tests
          command: ./buckw test //... --include unit --always_exclude
          shell: "/bin/bash"
workflows:
  version: 2
  build-test:
    jobs:
      - build
      - lint
      - unit
